import Footer from '@/components/Footer'
import { Urbanist } from 'next/font/google'
import './globals.css'
import { Inter } from 'next/font/google'
import Navbar from '@/components/Navbar'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Ecommerce store',
  description: 'Generated by create next app',
}
const font = Urbanist({ subsets: ['latin'] })

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={font.className}>
        <Navbar/>
        {children}
        <Footer />
      </body>
    </html>
  )
}
